baseURL = 'https://buzzy.gitee.io/synjones'
languageCode = 'en-us'
title = '常规产品'

theme = "hyde"
[Menus]
main = [
#{Name = "Github", URL = "https://github.com/username/"},
]
[params]
description = "刘刚的产品维护"
copyright = "Copyright (c) 2022, Logan"
